version: '3.4'
services:
  api_developers:
    image: api_developers
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
    driver: local

